### PR TITLE
Pull Request to fix Tags, Max-Width, BaseURL, and Title Repeating

### LINKED ISSUE #10: Duplicate content in title, Crab - Crab
In header.html partial there is {{ .Title }} - {{ .Site.Title }} but when you are on the home page .Title and .Site.Title are the same, and you get page title "Crab - Crab".

### LINKED ISSUE #11: Problem displaying Blogs
Hello, I am looking at moving a site at work to Hugo (Hugo Static Site Generator v0.36 darwin/amd64 BuildDate:) using this awesome theme on GitHub Pages. However, I ran into an issue showing the blog posts when I click on /blog.

When I have baseurl set to  ```baseurl = "/"```, I can see blog posts on /blog locally. the /blog/index.html is populated with the entries.

When set to ```baseurl = "https://rusher81572.github.io/seastar/"```, I do not see any blog posts on /blog. /blog/index.html is not populated with the entries.

Regardless of the baseurl, index.xml is populated correctly.

### LINKED ISSUE #12: Tags not populating properly
I am a big fan of the crab theme, and I have deployed it on my personal Hugo pages site. I have noticed one issue with it though, and I haven't been able to fix it through playing around with different options, CSS or configs.

I've deployed the theme and `exampleSite` content at https://oct8l.github.io/crab-example/ to demonstrate what I am running into. 

For example, if you click on the tag for "post" that all three blogs have, it takes you to a page that has the header of the tag, but it doesn't list any blogs that contain that tag (for example, the `post` tag at https://oct8l.github.io/crab-example/tags/post/)

Do you know if there are any changes I could make to get this working?

Thanks!

### PR DESCRIPTION
**Pull request by drowssaPdnAemanresU**
This pull request is to resolve Issue #10 , Issue #11 , Issue #12 , and Issue #14 
This pull request also fixes features.html, removes URL checking for lists, and replaces URL checking with Pagination. This closes #10, closes #11, and closes #12 as they are completely resolved. This pull request also adds Pagination navigation.

### CODE REVIEW

**Comment by oct8l** [comment]
Hey @drowssaPdnAemanresU, thanks for these changes in the PR. I love the theme and I appreciate you spending the time to get the last few issues opened on the repo sorted out.

**Comment by drowssaPdnAemanresU** [comment]
Thanks oct8l. I'm sorta new to github as a contributor and I only learned Hugo a few days ago to work on this template. Yeah, so, I'm gonna figure out how ".Site.Params.mainSections" works so I can add it in

**Comment by drowssaPdnAemanresU** [comment]
Okay, I've figured out everything and all of exampleSite should work after this pull request is approved.
Funnily enough, I found this theme on BountySource and decided to learn Hugo, It took about 2 days to learn most of it, and I started working on this theme and just decided "I may as well try to fix some other issues"

**Comment by drowssaPdnAemanresU** [comment]
I'm going to sleep for now. There are still bugs in my repository that I'll fix when I get up.

**Comment by drowssaPdnAemanresU** [comment]
All bugs have been squashed in my repository for now.
It has been updated and should be safe to use.

**Comment by drowssaPdnAemanresU** [comment]
I'm going to sleep

**Comment by oct8l** [comment]
@drowssaPdnAemanresU That's pretty cool that you found this through BountySource, I'm glad more talented people are involved with Hugo! There's a lot of good stuff in here, very awesome of you to take the time to figure out all of the open issues.

**Comment by drowssaPdnAemanresU** [comment]
Okay, I've tested everything and can confirm that everything in the current repository works.
If a page does not work, please make a post here. I will no longer be making my commits to my master branch by default, instead, I will be temporarily creating a Testing branch anytime I wish to add a feature or change a feature so that it can be tested before being put in main and so that people don't download the repository while something is being worked on.

**Comment by drowssaPdnAemanresU** [comment]
If anyone has downloaded my repository before me posting the above comment, please download the new theme from the master branch.

**Comment by drowssaPdnAemanresU** [comment]
I think I'll just be off, although hugo may be nice for some people, it is lacking in documentation and is fairly complicated to use. I'd tried to fix what I could. If anybody wishes to contribute to my branch, I'll accept any pull requests given that they work.

**Comment by thomasheller** [comment]
@drowssaPdnAemanresU I appreciate your effort, but frankly, putting so many changes in a single PR is just messy. If you still like to contribute, please open one PR per bugfix/feature.

Let's see if we can sort this out:

- #10 is resolved properly by now (see the discussion in the issue).
- #11 seems to be resolved, too. If there is still a problem, please open a new issue to discuss the proper solution.
- #12 can't be reproduced (see discussion). If the issue persits, please re-open that issue.
- #14 fixed by cherry-picking your commit 049adec. :+1:

I'm closing this PR for now. You're welcome to contribute, but as I said please open individual issues/PRs for each issue. Thanks!

**Pull request closed without merging**
